version: "3.9"
services:
  medial_symfony:
    build:
      context: ./containers/medial_symfony/
    container_name: medial_symfony
    ports:
      - 80:80
      - 8000:8000
    networks:
      frontend:
      backend:
    volumes:
      - ./symfony/:/var/www/html/
  mariadb:
    build:
      context: ./containers/db/
    container_name: medial_mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: webdev
      MARIADB_DATABASE: webdev
      MARIADB_USER: webdev
      MARIADB_PASSWORD: webdev
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
    - ./data/db/:/var/lib/db/
networks:
  frontend:
  backend: